/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.sh.ui.AbstractShellscriptUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ShellscriptUiModule extends AbstractShellscriptUiModule {
  public ShellscriptUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
