/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh;

import org.xtext.example.sh.ShellscriptStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ShellscriptStandaloneSetup extends ShellscriptStandaloneSetupGenerated {
  public static void doSetup() {
    new ShellscriptStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
