/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.tsc.ui.AbstractTypeScriptUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TypeScriptUiModule extends AbstractTypeScriptUiModule {
  public TypeScriptUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
