/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh.ide;

import org.xtext.example.sh.ide.AbstractShellscriptIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ShellscriptIdeModule extends AbstractShellscriptIdeModule {
}
