/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.sh.ShellscriptRuntimeModule;
import org.xtext.example.sh.ShellscriptStandaloneSetup;
import org.xtext.example.sh.ide.ShellscriptIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ShellscriptIdeSetup extends ShellscriptStandaloneSetup {
  @Override
  public Injector createInjector() {
    ShellscriptRuntimeModule _shellscriptRuntimeModule = new ShellscriptRuntimeModule();
    ShellscriptIdeModule _shellscriptIdeModule = new ShellscriptIdeModule();
    return Guice.createInjector(Modules2.mixin(_shellscriptRuntimeModule, _shellscriptIdeModule));
  }
}
