/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.example.tsc.services.TypeScriptGrammarAccess;
import org.xtext.example.tsc.typeScript.Greeting;
import org.xtext.example.tsc.typeScript.Model;
import org.xtext.example.tsc.typeScript.TypeScriptPackage;

@SuppressWarnings("all")
public class TypeScriptSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TypeScriptGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TypeScriptPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TypeScriptPackage.GREETING:
				sequence_Greeting(context, (Greeting) semanticObject); 
				return; 
			case TypeScriptPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Greeting returns Greeting
	 *
	 * Constraint:
	 *     (((expression=Expression+ | expression=Expression+)? name=TEXTOS) | name=TEXTOS)
	 */
	protected void sequence_Greeting(ISerializationContext context, Greeting semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     greetings+=Greeting+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
