/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.tsc.services.TypeScriptGrammarAccess;
import org.xtext.example.tsc.typeScript.Compute;
import org.xtext.example.tsc.typeScript.Model;
import org.xtext.example.tsc.typeScript.TypeScriptPackage;

@SuppressWarnings("all")
public class TypeScriptSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TypeScriptGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TypeScriptPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TypeScriptPackage.COMPUTE:
				sequence_Compute(context, (Compute) semanticObject); 
				return; 
			case TypeScriptPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Compute returns Compute
	 *
	 * Constraint:
	 *     (expression=Expression* name=STRING)
	 */
	protected void sequence_Compute(ISerializationContext context, Compute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     compute=Compute
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TypeScriptPackage.Literals.MODEL__COMPUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TypeScriptPackage.Literals.MODEL__COMPUTE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getModelAccess().getComputeComputeParserRuleCall_0(), semanticObject.getCompute());
		feeder.finish();
	}
	
	
}
