/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc.validation;

import org.xtext.example.tsc.validation.AbstractTypeScriptValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TypeScriptValidator extends AbstractTypeScriptValidator {
}
