/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.sh.parser.antlr.internal.InternalShellscriptParser;
import org.xtext.example.sh.services.ShellscriptGrammarAccess;

public class ShellscriptParser extends AbstractAntlrParser {

	@Inject
	private ShellscriptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalShellscriptParser createParser(XtextTokenStream stream) {
		return new InternalShellscriptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ShellscriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ShellscriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
