/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc.scoping;

import org.xtext.example.tsc.scoping.AbstractTypeScriptScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TypeScriptScopeProvider extends AbstractTypeScriptScopeProvider {
}
