/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ShellscriptStandaloneSetup extends ShellscriptStandaloneSetupGenerated {

	def static void doSetup() {
		new ShellscriptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
