/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractShellscriptScopeProvider extends DelegatingScopeProvider {
}
