/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh.ui.contentassist;

import org.xtext.example.sh.ui.contentassist.AbstractShellscriptProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ShellscriptProposalProvider extends AbstractShellscriptProposalProvider {
}
