/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc.ide;

import org.xtext.example.tsc.ide.AbstractTypeScriptIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TypeScriptIdeModule extends AbstractTypeScriptIdeModule {
}
