/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.sh.ui.internal.ShActivator;

public class ShellscriptUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ShActivator.getInstance().getInjector("org.xtext.example.sh.Shellscript");
	}

}
