/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.tsc.parser.antlr.internal.InternalTypeScriptParser;
import org.xtext.example.tsc.services.TypeScriptGrammarAccess;

public class TypeScriptParser extends AbstractAntlrParser {

	@Inject
	private TypeScriptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTypeScriptParser createParser(XtextTokenStream stream) {
		return new InternalTypeScriptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TypeScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TypeScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
