/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTypeScriptValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.tsc.typeScript.TypeScriptPackage.eINSTANCE);
		return result;
	}
	
}
