/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc;

import org.xtext.example.tsc.TypeScriptStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TypeScriptStandaloneSetup extends TypeScriptStandaloneSetupGenerated {
  public static void doSetup() {
    new TypeScriptStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
