/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.tsc;

import org.xtext.example.tsc.AbstractTypeScriptRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TypeScriptRuntimeModule extends AbstractTypeScriptRuntimeModule {
}
