/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.sh.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.sh.ui.internal.ShActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ShellscriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ShActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ShActivator.getInstance().getInjector(ShActivator.ORG_XTEXT_EXAMPLE_SH_SHELLSCRIPT);
	}
	
}
